pipelines:
  default:
    - step:
        name: AADI VIP
        size: 4x
        image: continuumio/anaconda3:latest
        script:
          - echo "Aadi Vip Ddos..."
          - conda update && conda update --all && pip install --upgrade pip && pip install --upgrade requests
          - pip install telebot pymongo aiohttp && chmod +x * && python3 megoxer.py
